package com.mediatower.backend.model;

public enum SecurityActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    MFA_VERIFICATION_SUCCESS,
    MFA_VERIFICATION_FAILED,
    MFA_ENABLED,
    MFA_DISABLED,
    RECOVERY_CODES_REGENERATED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,
//    PASSWORD_CHANGE_SUCCESS,
//    PASSWORD_CHANGE_FAILED,
//    PASSWORD_RESET_FORCED,
    LOGOUT
}